### ISSUE TITLE
Remove inline style for svg icons

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#5744]
In most cases we need to theme our svg icons and the inline styles may accidentally break the theming we apply elsewhere. These inline styles are almost of no use so we should remove them.

## Steps to convert to icon components

1. Where possible, swap out old usages of icons for icon components and registered icon names. Examples:

    ```html
    <!-- Icon binding with literal value -->
    <div class="some-class" data-bind="icon: './path/to/Icon.svg'"></div>

    <div class="some-class">
      <se-icon params="with: { name: 'Icon' }"></se-icon>
    </div>
    ```

    ```html
    <!-- Icon binding with observable -->
    <div class="some-class" data-bind="icon: someIcon"></div>

    <div class="some-class">
      <se-icon params="with: { name: someIcon }"></se-icon>
    </div>
    ```

    ```html
    <!-- Image element -->
    <img class="some-class" data-bind="attr: { src: '.path/to/Icon.svg' }" />

    <div class="some-class">
      <se-icon params="with: { name: 'Icon' }"></se-icon>
    </div>
    ```

    ```html
    <!-- Progress ring or "spinner" -->
    <div class="spinner" data-bind="icon: './path/to/ProgressSpinner.svg'"></div>

    <se-progress-ring params="with: { themed: true }"></se-progress-ring>
    ```

2. Duplicate or custom style rules should be replaced with imported component styles. Key frames and animations for progress rings should also be replaced. Rules that set the icon size, however, should remain in place.

    ```less
    @import (less) "../node_models/@storage-explorer/ui-components/dist/src/Styles/Alert.css";
    @import (less) "../node_models/@storage-explorer/ui-components/dist/src/Styles/ProgressRing.css";

    .some-class {
        height: 16px;
        width: 16px;
    }
    ```

    Some "composite" styles may have rules that need to be overridden. For example, the Dialogs.css file contains styles for alert components that can interfere with those in Alert.css. These will eventually be fixed once all dialogs are updated properly.

3. Rules for theming icons should be updated with class names used in the components.

    ```less
    .some-class {
        height: 16px;
        width: 16px;

        .icon svg.themed * {
            fill: var(--color-text);
        }
    }
    ```

4. Make sure the entry/index file initializes the icon loader.

   ```ts
   import { IconLoader } from "@storage-explorer/ui-components";
   import { IconManager } from "./Sdk";

   (async () => {
       await IconLoader.initialize(IconManager);
       
       ...
   })();
   ```
