### ISSUE TITLE
'latest' version is pointing to 1.29.3

### ISSUE THREAD

**Issue by jrineck** [microsoft/AzureStorageExplorer#7387]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2

### Regression From

1.30.1

### Architecture

x64

### Platform

Linux (tar.gz)

### OS Version

Ubuntu 20.04

### Bug Description

We dynamically pull the 'latest' version using the tag_name from this JSON [api.github.com/repos/microsoft/AzureStorageExplorer/releases/latest](https://api.github.com/repos/microsoft/AzureStorageExplorer/releases/latest) file using the `tag_name` attribute.  Currently the 'latest' tag for Azure Storage Explorer is pointing to v1.29.3 from this file, which it does not match up with https://github.com/microsoft/AzureStorageExplorer/releases, where 'latest' would be v1.31.2

### Steps to Reproduce

1. Navigate to [Azure Storage Explorer | Releases | Latest](https://github.com/microsoft/AzureStorageExplorer/releases/latest)

It is pointing to v1.29.3 and not v1.31.2

### Actual Experience

JSON [api.github.com/repos/microsoft/AzureStorageExplorer/releases/latest](https://api.github.com/repos/microsoft/AzureStorageExplorer/releases/latest) file has `tag_name` attribute = v1.29.3

### Expected Experience

JSON [api.github.com/repos/microsoft/AzureStorageExplorer/releases/latest](https://api.github.com/repos/microsoft/AzureStorageExplorer/releases/latest) file should have `tag_name` attribute set to latest release, which is  = v1.31.2

**Comment by cpressland** [comment]
As per the above mention, this is also breaking automated installs on macOS that use Installomator. Please can we get the release pinned correctly?

**Comment by MRayermannMSFT** [comment]
> Currently the 'latest' tag for Azure Storage Explorer is pointing to v1.29.3 from this file, which it does not match up with

> As per the above mention, this is also breaking automated installs on macOS that use Installomator. Please can we get the release pinned correctly?

Ok this should now be fixed:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/c3082c17-0bb2-413a-ad1e-2fccf7f7bc1f)


> We dynamically pull the 'latest' version using the tag_name from this JSON

@jrineck, Is "We" an open source tool or internal tool? Just wondering, as we try to keep track of other means people have of grabbing Storage Explorer, in the hopes of being able to try and not break them.

**Comment by jrineck** [comment]
@MRayermannMSFT, apologies for the lack of clarity.  Our DevOps team uses Ansible tasks to download the latest version of Azure Storage Explorer - for both Windows and Linux - to an Azure Storage Account as we do not permit any firewall traffic to Github from our Azure VMs (secure enclave design); this in turn becomes the source files for Azure Storage Explorer installs on our VMs.  The logic of our Ansible tasks to fetch the 'latest' release:

```
---
- name: Determine latest GitHub release (local)
  ansible.builtin.uri:
    url: "https://api.github.com/repos/microsoft/AzureStorageExplorer/releases/latest"
    body_format: json
  register: github_release
  until: github_release.status == 200
  retries: 5

- name: Set azse_version
  ansible.builtin.set_fact:
    azse_version: "{{ github_release.json.tag_name
      | regex_replace('^v?([0-9\\.]+)$', '\\1') }}"
  when: >
    azse_version is match("latest")

- name: Login with az-cli
  ansible.builtin.command: |
    az login \
    --service-principal -u "{{ lookup('env', 'AZURE_CLIENT_ID') }}" \
    -p "{{ lookup('env', 'AZURE_SECRET') }}" \
    --tenant "{{ lookup('env', 'AZURE_TENANT') }}"
  no_log: true
  changed_when: false

- name: Set subscription_id
  ansible.builtin.command:
    cmd: az account set --subscription "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
  changed_when: false

## Download Linux Version
# yamllint disable rule:line-length
- name: Set azse_download_url
  ansible.builtin.set_fact:
    azse_lnx_download_url: "https://github.com/microsoft/AzureStorageExplorer/releases/download/v{{ azse_version }}/StorageExplorer-linux-x64.tar.gz"
# yamllint enable rule:line-length

- name: Check if package exists (Linux)
  ansible.builtin.command: |
    az storage blob exists \
        --auth-mode login \
        --account-name "_REDACTED_" \
        --container-name "_REDACTED_" \
        --name "StorageExplorer-{{ azse_version }}-linux-x64.tar.gz"
  register: azse_lnx_exists
  changed_when: not (azse_lnx_exists.stdout | from_json).exists

- name: Upload package to container (Linux)
  when: not (azse_lnx_exists.stdout | from_json).exists
  block:

    - name: Download current azse to local /tmp (Linux)
      ansible.builtin.get_url:
        url: "{{ azse_lnx_download_url }}"
        dest: "/tmp/StorageExplorer-{{ azse_version }}-linux-x64.tar.gz"
        mode: '0664'
      register: azse_lnx_download

    - name: Upload package to Azure Storage Blob (Linux)
      ansible.builtin.command: |
        az storage blob upload \
            --auth-mode login \
            --account-name "_REDACTED_" \
            --container-name "_REDACTED_" \
            --name "StorageExplorer-{{ azse_version }}-linux-x64.tar.gz" \
            --file "{{ azse_lnx_download.dest }}"
      register: azse_lnx_upload
      changed_when: false

    - name: Remove local file (Linux)
      ansible.builtin.file:
        path: "{{ azse_lnx_download.dest }}"
        state: absent

## Download Windows Version
# yamllint disable rule:line-length
- name: Set azse_download_url (Windows)
  ansible.builtin.set_fact:
    azse_win_download_url: "https://github.com/microsoft/AzureStorageExplorer/releases/download/v{{ azse_version }}/StorageExplorer-windows-x64.exe"
# yamllint enable rule:line-length

- name: Check if package exists (Windows)
  ansible.builtin.command: |
    az storage blob exists \
        --auth-mode login \
        --account-name "_REDACTED_" \
        --container-name "_REDACTED_" \
        --name "StorageExplorer-{{ azse_version }}-windows-x64.exe"
  register: azse_win_exists
  changed_when: not (azse_win_exists.stdout | from_json).exists

- name: Upload package to container (Windows)
  when: not (azse_win_exists.stdout | from_json).exists
  block:

    - name: Download current azse to local /tmp (Windows)
      ansible.builtin.get_url:
        url: "{{ azse_win_download_url }}"
        dest: "/tmp/StorageExplorer-{{ azse_version }}-windows-x64.exe"
        mode: '0664'
      register: azse_win_download

    - name: Upload package to Azure Storage Blob (Windows)
      ansible.builtin.command: |
        az storage blob upload \
            --auth-mode login \
            --account-name "_REDACTED_" \
            --container-name "_REDACTED_" \
            --name "StorageExplorer-{{ azse_version }}-windows-x64.exe" \
            --file "{{ azse_win_download.dest }}"
      register: azse_win_upload
      changed_when: false

    - name: Remove local file (Windows)
      ansible.builtin.file:
        path: "{{ azse_win_download.dest }}"
        state: absent
```

Any recommendations to this strategy based on extended knowledge of the Azure Storage Explorer development practices is welcome.  Thanks again for the fix!
