### ISSUE TITLE
Use config file to de-duplicate Node version in all build definitions

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#7688]
The task would look like:

```
- task: NodeTool@0
  displayName: 'Use Node'
  inputs:
    versionSource: fromFile
    versionFilePath: .nvmrc
```

In the .nvmrc, suppose we want to use Node v18.18.x, we will write
```
18.18
```
