### ISSUE TITLE
Add icon for symlink

### ISSUE THREAD

**Issue by bakoontz2** [microsoft/AzureStorageExplorer#8270]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Differentiate symlinks from documents (both use the same icon)

### Desired Solution

An icon that represents a symlink

### Alternatives and Workarounds

No workaround, it is what it is right now

**Comment by bakoontz2** [comment]
Reference: #7973 

I was asked to reopen this feature request with additional information.  The original writeup can be found in the referenced feature request linked above.  The additional requested info:

The file shares are created in the Azure portal as standard file shares, no share-level permissions, 14-day soft delete, 100TiB, maximum compatibility security (the defaults).  These files share are mounted to their respective K8S containers via pre-defined PV/PVCs:

pv.yaml
```
spec:
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: some-secret
    secretNamespace: some-ns
    shareName: some-share-name
  capacity:
    storage: 100Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: some-pvc
    namespace: some-ns
    resourceVersion: "12345678"
    uid: <guid>
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

pvc.yaml
```
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: some-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Ti
  phase: Bound
```

job.yaml
```
...
    volumeMounts:
    - mountPath: /mnt
      name: mnt
...
  volumes:
  - name: mnt
    persistentVolumeClaim:
      claimName: some-pvc
```

From there, we create the symlinks that are needed on the mounted filesystem using "ln -s".  

I really have no idea if this is SMB or NFS.  This is how the fileshares are mounted and used.

And I just noticed I need to open a new feature request, so I will do that with this comment.
